apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
#create key-value pairs here
  mongo-user: bQBvAG4AZwBvAHUAcwBlAHIA
  mongo-password: bQBvAG4AZwBvAHAAYQBzAHMAdwBvAHIAZAA=